name: bonuslink
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - matplotlib-inline=0.1.7
  - pip=25.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywin32=307
  - pyzmq=26.4.0
  - setuptools=78.1.1
  - pip:
      - boto3==1.38.36
      - matplotlib==3.10.3
      - numpy==2.2.6
      - pandas==2.3.0
      - pendulum==3.1.0
      - polars==1.30.0
      - pyarrow==20.0.0
      - scikit-learn==1.7.0
      - s3fs
      - seaborn
